[package]
name = "near-store"
version = "2.2.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
derive_more = "0.99.3"
elastic-array = "0.11"
lazy_static = "1.4"
rocksdb = { version = "0.15.0",  optional = true }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
cached = "0.12"
num_cpus = "1.11"
rand = "0.7.2"
strum = "0.18"
strum_macros = "0.18"

borsh = "0.7.1"

near-crypto = { path = "../crypto" }
near-primitives = { path = "../primitives" }

[dev-dependencies]
tempfile = "3"
bencher = "0.1.5"
rand = "0.7"

[[bench]]
name = "trie_bench"
harness = false

[features]
default = ["rocksdb"]
no_cache = []
adversarial = []
protocol_feature_rectify_inflation = []
nightly_protocol = []
nightly_protocol_features = ["nightly_protocol", "protocol_feature_rectify_inflation"]

[package.metadata.workspaces]
independent = true
